ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "color" TEXT NOT NULL DEFAULT '#ADC6FF';
ALTER TABLE "Territory" ADD COLUMN IF NOT EXISTS "polygon" JSONB;
ALTER TABLE "Territory" ADD COLUMN IF NOT EXISTS "area" DOUBLE PRECISION NOT NULL DEFAULT 0;
